pip install flask
pip install flask-login
pip install flask-openid
pip install flask-migrate
pip install flask-script
pip install sqlalchemy
pip install flask-sqlalchemy
pip install sqlalchemy-migrate
pip install flask-whooshalchemy
pip install flask-wtf
pip install pytz
pip install flask-babel
pip install flup