pip install sqlalchemy
pip install flask
pip install flask-sqlalchemy
pip install flask-migrate
pip install flask-script
pip install flask-wtf
pip install flask-login
pip install flask-bootstrap
pip install flask-whooshalchemy
pip install flask-mail
pip install email_validator
pip install pyjwt